### ISSUE TITLE
默认npm run dev下报错

### ISSUE THREAD

**Issue by cometwan** [deepkolos/wxmp-tensorflow#1]
error: Invalid option in transform() call: "jsx"

**Comment by cometwan** [comment]
又试了便pnpm 正常了。

**Comment by chen-yt** [comment]
这个问题复现了～
```
[!] (plugin esbuild) Error: Transform failed with 1 error:
error: Invalid option in transform() call: "jsx"
miniprogram/pages/handpose/handpose.ts
Error: Transform failed with 1 error:
error: Invalid option in transform() call: "jsx"
    at failureErrorWithLog (/Users/joson/Desktop/wxmp-tensorflow/node_modules/esbuild/lib/main.js:1443:15)
    at /Users/joson/Desktop/wxmp-tensorflow/node_modules/esbuild/lib/main.js:1288:20
    at /Users/joson/Desktop/wxmp-tensorflow/node_modules/esbuild/lib/main.js:606:9
    at handleIncomingPacket (/Users/joson/Desktop/wxmp-tensorflow/node_modules/esbuild/lib/main.js:703:9)
    at Socket.readFromStdout (/Users/joson/Desktop/wxmp-tensorflow/node_modules/esbuild/lib/main.js:573:7)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```
